pipeline {
    agent {
        dockerfile {
            dir 'docker/cicd' 
        } 
    }
    stages {
        stage('build') {
            steps {
                sh 'pipenv install'
            }
        }
        // stage('lint') {
        //     steps {
        //         sh 'pipenv run flake8'
        //     }
        // }
        stage('unittest') {
            steps {
                sh 'pipenv run python3 -m unittest'
            }
        }
    }
}
