// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model.proto

It has these top-level messages:
	InstanceTemplate
	LxcInstanceTemplate
	NullInstanceTemplate
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NullInstanceTemplate_CrashStage int32

const (
	NullInstanceTemplate_NONE  NullInstanceTemplate_CrashStage = 0
	NullInstanceTemplate_START NullInstanceTemplate_CrashStage = 1
)

var NullInstanceTemplate_CrashStage_name = map[int32]string{
	0: "NONE",
	1: "START",
}
var NullInstanceTemplate_CrashStage_value = map[string]int32{
	"NONE":  0,
	"START": 1,
}

func (x NullInstanceTemplate_CrashStage) String() string {
	return proto.EnumName(NullInstanceTemplate_CrashStage_name, int32(x))
}
func (NullInstanceTemplate_CrashStage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 0}
}

type InstanceTemplate struct {
	// Types that are valid to be assigned to Item:
	//	*InstanceTemplate_None
	//	*InstanceTemplate_Null
	Item isInstanceTemplate_Item `protobuf_oneof:"Item"`
}

func (m *InstanceTemplate) Reset()                    { *m = InstanceTemplate{} }
func (m *InstanceTemplate) String() string            { return proto.CompactTextString(m) }
func (*InstanceTemplate) ProtoMessage()               {}
func (*InstanceTemplate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isInstanceTemplate_Item interface {
	isInstanceTemplate_Item()
}

type InstanceTemplate_None struct {
	None *LxcInstanceTemplate `protobuf:"bytes,500,opt,name=none,oneof"`
}
type InstanceTemplate_Null struct {
	Null *NullInstanceTemplate `protobuf:"bytes,502,opt,name=null,oneof"`
}

func (*InstanceTemplate_None) isInstanceTemplate_Item() {}
func (*InstanceTemplate_Null) isInstanceTemplate_Item() {}

func (m *InstanceTemplate) GetItem() isInstanceTemplate_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *InstanceTemplate) GetNone() *LxcInstanceTemplate {
	if x, ok := m.GetItem().(*InstanceTemplate_None); ok {
		return x.None
	}
	return nil
}

func (m *InstanceTemplate) GetNull() *NullInstanceTemplate {
	if x, ok := m.GetItem().(*InstanceTemplate_Null); ok {
		return x.Null
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*InstanceTemplate) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _InstanceTemplate_OneofMarshaler, _InstanceTemplate_OneofUnmarshaler, _InstanceTemplate_OneofSizer, []interface{}{
		(*InstanceTemplate_None)(nil),
		(*InstanceTemplate_Null)(nil),
	}
}

func _InstanceTemplate_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*InstanceTemplate)
	// Item
	switch x := m.Item.(type) {
	case *InstanceTemplate_None:
		b.EncodeVarint(500<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.None); err != nil {
			return err
		}
	case *InstanceTemplate_Null:
		b.EncodeVarint(502<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Null); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("InstanceTemplate.Item has unexpected type %T", x)
	}
	return nil
}

func _InstanceTemplate_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*InstanceTemplate)
	switch tag {
	case 500: // Item.none
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LxcInstanceTemplate)
		err := b.DecodeMessage(msg)
		m.Item = &InstanceTemplate_None{msg}
		return true, err
	case 502: // Item.null
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NullInstanceTemplate)
		err := b.DecodeMessage(msg)
		m.Item = &InstanceTemplate_Null{msg}
		return true, err
	default:
		return false, nil
	}
}

func _InstanceTemplate_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*InstanceTemplate)
	// Item
	switch x := m.Item.(type) {
	case *InstanceTemplate_None:
		s := proto.Size(x.None)
		n += proto.SizeVarint(500<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *InstanceTemplate_Null:
		s := proto.Size(x.Null)
		n += proto.SizeVarint(502<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type LxcInstanceTemplate struct {
	Vcpu int32 `protobuf:"varint,1,opt,name=vcpu" json:"vcpu,omitempty"`
}

func (m *LxcInstanceTemplate) Reset()                    { *m = LxcInstanceTemplate{} }
func (m *LxcInstanceTemplate) String() string            { return proto.CompactTextString(m) }
func (*LxcInstanceTemplate) ProtoMessage()               {}
func (*LxcInstanceTemplate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LxcInstanceTemplate) GetVcpu() int32 {
	if m != nil {
		return m.Vcpu
	}
	return 0
}

type LxcInstanceTemplate_Image struct {
	DownloadUrl string `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl" json:"download_url,omitempty"`
}

func (m *LxcInstanceTemplate_Image) Reset()                    { *m = LxcInstanceTemplate_Image{} }
func (m *LxcInstanceTemplate_Image) String() string            { return proto.CompactTextString(m) }
func (*LxcInstanceTemplate_Image) ProtoMessage()               {}
func (*LxcInstanceTemplate_Image) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *LxcInstanceTemplate_Image) GetDownloadUrl() string {
	if m != nil {
		return m.DownloadUrl
	}
	return ""
}

type NullInstanceTemplate struct {
	Vcpu int32 `protobuf:"varint,1,opt,name=vcpu" json:"vcpu,omitempty"`
}

func (m *NullInstanceTemplate) Reset()                    { *m = NullInstanceTemplate{} }
func (m *NullInstanceTemplate) String() string            { return proto.CompactTextString(m) }
func (*NullInstanceTemplate) ProtoMessage()               {}
func (*NullInstanceTemplate) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *NullInstanceTemplate) GetVcpu() int32 {
	if m != nil {
		return m.Vcpu
	}
	return 0
}

func init() {
	proto.RegisterType((*InstanceTemplate)(nil), "model.InstanceTemplate")
	proto.RegisterType((*LxcInstanceTemplate)(nil), "model.LxcInstanceTemplate")
	proto.RegisterType((*LxcInstanceTemplate_Image)(nil), "model.LxcInstanceTemplate.Image")
	proto.RegisterType((*NullInstanceTemplate)(nil), "model.NullInstanceTemplate")
	proto.RegisterEnum("model.NullInstanceTemplate_CrashStage", NullInstanceTemplate_CrashStage_name, NullInstanceTemplate_CrashStage_value)
}

func init() { proto.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4b, 0x03, 0x31,
	0x14, 0x80, 0x1b, 0x4c, 0x8a, 0x7d, 0xe7, 0x70, 0x44, 0x87, 0xa3, 0x2e, 0x6d, 0xa6, 0xe2, 0x50,
	0xb0, 0xfe, 0x02, 0x15, 0xc1, 0x03, 0x3d, 0x21, 0xbd, 0xce, 0x12, 0xef, 0x82, 0x0e, 0x2f, 0xc9,
	0x91, 0x26, 0xea, 0xea, 0x7f, 0x16, 0x67, 0x31, 0xa7, 0x8b, 0x64, 0x4b, 0x1e, 0xdf, 0xf7, 0x3d,
	0x78, 0x50, 0x18, 0xd7, 0x6b, 0x5c, 0x0f, 0xde, 0x05, 0xc7, 0x59, 0xfa, 0x88, 0x0f, 0x02, 0x65,
	0x6d, 0xf7, 0x41, 0xd9, 0x4e, 0xb7, 0xda, 0x0c, 0xa8, 0x82, 0xe6, 0xe7, 0x40, 0xad, 0xb3, 0xba,
	0xfa, 0x3c, 0x58, 0x90, 0x55, 0xb1, 0x99, 0xaf, 0x47, 0xf1, 0xee, 0xbd, 0xfb, 0x8f, 0xde, 0x4e,
	0x64, 0x42, 0xf9, 0x06, 0xa8, 0x8d, 0x88, 0xd5, 0xd7, 0xa8, 0x9c, 0xfe, 0x2a, 0x4d, 0x44, 0xcc,
	0x3a, 0x11, 0xf1, 0x6a, 0x0a, 0xb4, 0x0e, 0xda, 0x88, 0x1d, 0x1c, 0x67, 0xd2, 0x9c, 0x03, 0x7d,
	0xed, 0x86, 0x58, 0x91, 0x05, 0x59, 0x31, 0x99, 0xde, 0xf3, 0x33, 0x60, 0xb5, 0x51, 0xcf, 0x9a,
	0x2f, 0xe1, 0xa8, 0x77, 0x6f, 0x16, 0x9d, 0xea, 0x1f, 0xa3, 0xc7, 0x04, 0xcd, 0x64, 0xf1, 0x37,
	0xdb, 0x79, 0x14, 0xf7, 0x70, 0x92, 0x5b, 0x9f, 0xeb, 0x8a, 0x25, 0xc0, 0xb5, 0x57, 0xfb, 0x97,
	0x6d, 0xf8, 0x89, 0x1f, 0x02, 0x6d, 0x1e, 0x9a, 0x9b, 0x72, 0xc2, 0x67, 0xc0, 0xb6, 0xed, 0xa5,
	0x6c, 0x4b, 0xf2, 0x34, 0x4d, 0x77, 0xbb, 0xf8, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x3b, 0xbe,
	0x27, 0x46, 0x01, 0x00, 0x00,
}
